"""link scan candidates to instruments

Revision ID: 152a2a525c7c
Revises: 8541d0ead096
Create Date: 2026-07-23 22:24:25.173978

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "152a2a525c7c"
down_revision: str | Sequence[str] | None = "8541d0ead096"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_candidates", schema=None) as batch_op:
        batch_op.add_column(sa.Column("instrument_id", sa.Uuid(), nullable=True))
        batch_op.alter_column(
            "symbol",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=20),
            existing_nullable=False,
        )
        batch_op.create_index(
            "ix_scan_candidates_instrument_id",
            ["instrument_id"],
            unique=False,
        )
        batch_op.create_unique_constraint(
            "uq_scan_candidates_scan_run_instrument",
            ["scan_run_id", "instrument_id"],
        )
        batch_op.create_foreign_key(
            "fk_scan_candidates_instrument_id",
            "instruments",
            ["instrument_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_candidates", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_scan_candidates_instrument_id",
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            "uq_scan_candidates_scan_run_instrument",
            type_="unique",
        )
        batch_op.drop_index("ix_scan_candidates_instrument_id")
        batch_op.alter_column(
            "symbol",
            existing_type=sa.String(length=20),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )
        batch_op.drop_column("instrument_id")
    # ### end Alembic commands ###
