"""create scan candidates table

Revision ID: 52d6ded66a8f
Revises: 71dc6e689e32
Create Date: 2026-07-23 19:49:38.739643

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52d6ded66a8f"
down_revision: str | Sequence[str] | None = "71dc6e689e32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scan_run_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("composite_score", sa.Float(), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_run_id"], ["scan_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scan_run_id", "symbol", name="uq_scan_candidates_scan_run_symbol"
        ),
    )
    op.create_index(
        op.f("ix_scan_candidates_scan_run_id"),
        "scan_candidates",
        ["scan_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scan_candidates_symbol"), "scan_candidates", ["symbol"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scan_candidates_symbol"), table_name="scan_candidates")
    op.drop_index(op.f("ix_scan_candidates_scan_run_id"), table_name="scan_candidates")
    op.drop_table("scan_candidates")
    # ### end Alembic commands ###
