"""create_instruments_table

Revision ID: 8541d0ead096
Revises: 52d6ded66a8f
Create Date: 2026-07-23 21:16:34.163016

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8541d0ead096"
down_revision: str | Sequence[str] | None = "52d6ded66a8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("exchange", sa.String(length=100), nullable=True),
        sa.Column(
            "asset_type",
            sa.Enum(
                "STOCK", "ETF", "ADR", name="instrumentassettype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instruments_symbol"), "instruments", ["symbol"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_instruments_symbol"), table_name="instruments")
    op.drop_table("instruments")
    # ### end Alembic commands ###
